export const activities = [
  {
    id: "honggui-cake",
    aliases: ["紅龜粿手作"],
    category: "報名手作",
    title: "傳統炊粿・紅龜粿手作",
    shortTitle: "紅龜粿手作",
    day: "12",
    month: "MAY",
    weekday: "二",
    dateLabel: "12 MAY (二)",
    time: "14:00 - 16:30",
    duration: "2.5 hr",
    registered: 6,
    capacity: 8,
    price: 980,
    unit: "人",
    location: "老屋廚趣",
    address: "台南市中西區民權路二段 30 號",
    instructor: "陳阿嬤",
    summary: "百年大灶起火，跟著阿嬤揉拌粿、印粿、上蒸籠。每人帶 6 顆紅龜粿回家。",
    heroClass: "from-[#00875f] to-[#14b983]",
    highlights: ["體驗百年大灶傳統炊粿", "學習揉麵、包餡、印模技巧", "了解紅龜粿的文化意義", "每人帶走 6 顆手作紅龜粿"],
    notes: ["適合 12 歲以上參加", "請穿著輕便服裝", "建議提前 10 分鐘到達"],
  },
  {
    id: "rice-harvest",
    aliases: ["清晨割稻體驗"],
    category: "農事體驗",
    title: "清晨割稻・田間早餐",
    shortTitle: "清晨割稻體驗",
    day: "14",
    month: "MAY",
    weekday: "四",
    dateLabel: "14 MAY (四)",
    time: "06:00 - 09:00",
    duration: "3 hr",
    registered: 4,
    capacity: 10,
    price: 1200,
    unit: "人",
    location: "後埕稻田",
    address: "台南市後壁區稻田路 18 號",
    instructor: "林伯伯",
    summary: "清晨走進稻田，學習割稻與綁稻，最後在田邊享用熱粥與小菜早餐。",
    heroClass: "from-[#6f8f24] to-[#b5a23e]",
    highlights: ["體驗傳統割稻與綁稻", "認識稻作與節氣", "田邊早餐", "帶回一束稻穗紀念"],
    notes: ["請穿防滑鞋", "活動可能因天候調整", "建議攜帶帽子與水壺"],
  },
  {
    id: "plum-wine",
    aliases: ["立夏限定 · 青梅釀酒", "青梅釀酒"],
    category: "節氣釀造",
    title: "立夏限定・青梅釀酒",
    shortTitle: "青梅釀酒",
    day: "16",
    month: "MAY",
    weekday: "六",
    dateLabel: "16 MAY (六)",
    time: "13:30 - 15:30",
    duration: "2 hr",
    registered: 7,
    capacity: 8,
    price: 680,
    unit: "人",
    location: "老屋中庭",
    address: "台南市中西區民權路二段 30 號",
    instructor: "吳釀師",
    summary: "挑青梅、洗梅、殺青與封罐，帶回一瓶屬於自己的夏日梅酒。",
    heroClass: "from-[#789028] to-[#c0a243]",
    highlights: ["認識青梅處理流程", "完成個人梅酒封罐", "學習保存與飲用時程", "帶回 1 罐青梅酒"],
    notes: ["未滿 18 歲不得飲酒", "可改做無酒精梅露", "請提前 10 分鐘到場"],
  },
  {
    id: "kiln-building",
    aliases: ["古法砌窯"],
    category: "在地職人",
    title: "磚瓦匠的手・古法砌窯",
    shortTitle: "古法砌窯",
    day: "18",
    month: "MAY",
    weekday: "一",
    dateLabel: "18 MAY (一)",
    time: "10:00 - 16:00",
    duration: "6 hr",
    registered: 0,
    capacity: 6,
    price: 1480,
    unit: "人",
    location: "後埕窯場",
    address: "台南市後壁區窯場路 8 號",
    instructor: "黃師傅",
    summary: "與第三代瓦窯師傅共工一日，學疊磚、抹漿、修簷，午餐自烤披薩。",
    heroClass: "from-[#7d1d0f] to-[#a85639]",
    highlights: ["學習古法砌窯工序", "理解磚瓦與老屋修復", "職人現場示範", "午餐自烤披薩"],
    notes: ["請穿可弄髒衣物", "活動含午餐", "不建議 12 歲以下單獨參加"],
  },
  {
    id: "feed-chicken",
    aliases: ["餵雞拾蛋"],
    category: "親子同遊",
    title: "小田農夫・餵雞拾蛋",
    shortTitle: "餵雞拾蛋",
    day: "21",
    month: "MAY",
    weekday: "四",
    dateLabel: "21 MAY (四)",
    time: "15:30 - 17:00",
    duration: "1.5 hr",
    registered: 5,
    capacity: 12,
    price: 780,
    unit: "親子組",
    location: "老屋後院",
    address: "台南市中西區民權路二段 30 號",
    instructor: "小田老師",
    summary: "給小朋友的第一堂農事課：認識三隻土雞、餵食、撿溫熱的蛋回家。",
    heroClass: "from-[#007a83] to-[#70bca9]",
    highlights: ["認識土雞生活習性", "親手餵食與撿蛋", "完成小農夫任務卡", "帶回新鮮雞蛋"],
    notes: ["適合親子同行", "請穿耐髒鞋", "現場需家長陪同"],
  },
  {
    id: "firefly-walk",
    aliases: ["螢火夜行"],
    category: "獨處時光",
    title: "螢火夜行・後山步道",
    shortTitle: "螢火夜行",
    day: "23",
    month: "MAY",
    weekday: "六",
    dateLabel: "23 MAY (六)",
    time: "19:30 - 21:00",
    duration: "1.5 hr",
    registered: 12,
    capacity: 12,
    price: 450,
    unit: "人",
    location: "後山步道入口",
    address: "台南市後壁區後山步道入口",
    instructor: "阿哲嚮導",
    summary: "熄燈隨自然生光。在地嚮導帶你走 1.6km 步道，認識螢火蟲與夜間生物。",
    heroClass: "from-[#23335d] to-[#316b73]",
    highlights: ["夜間生態導覽", "認識螢火蟲棲地", "低光害步道體驗", "小班制慢行"],
    notes: ["請勿使用強光手電筒", "請穿長袖長褲", "此活動已額滿可候補"],
  },
  {
    id: "savory-rice-cake",
    aliases: ["鹹粿菜頭粿"],
    category: "飲食手作",
    title: "柴燒手作・鹹粿與菜頭粿",
    shortTitle: "鹹粿菜頭粿",
    day: "26",
    month: "MAY",
    weekday: "二",
    dateLabel: "26 MAY (二)",
    time: "10:00 - 12:30",
    duration: "2.5 hr",
    registered: 3,
    capacity: 8,
    price: 880,
    unit: "人",
    location: "老屋灶腳",
    address: "台南市中西區民權路二段 30 號",
    instructor: "阿桂阿姨",
    summary: "使用在地白米與蘿蔔，跟著阿桂阿姨的私房比例，蒸出最有家的味道的粿。",
    heroClass: "from-[#8a6419] to-[#d0a444]",
    highlights: ["學習米漿比例", "處理蘿蔔與鹹料", "柴燒蒸籠體驗", "帶回自製菜頭粿"],
    notes: ["活動含試吃", "請自備保鮮盒", "可素食請提前告知"],
  },
  {
    id: "morning-walk",
    aliases: ["晨間靜走"],
    category: "獨處時光",
    title: "晨間靜走・田埂之間",
    shortTitle: "晨間靜走",
    day: "28",
    month: "MAY",
    weekday: "四",
    dateLabel: "28 MAY (四)",
    time: "06:30 - 07:30",
    duration: "1 hr",
    registered: 2,
    capacity: 8,
    price: 380,
    unit: "人",
    location: "老屋門口集合",
    address: "台南市中西區民權路二段 30 號",
    instructor: "阿曼老師",
    summary: "不講話，跟著嚮導以慢速走過 2km 田埂。回程奉上一杯熱玄米茶。",
    heroClass: "from-[#00645e] to-[#66a98f]",
    highlights: ["田埂慢行", "呼吸與步伐練習", "晨間觀察筆記", "回程熱玄米茶"],
    notes: ["請準時集合", "建議穿輕便鞋", "雨天改為室內靜心茶席"],
  },
  {
    id: "summer-vegetable",
    aliases: ["夏蔬採收"],
    category: "節氣 · 小滿",
    title: "小滿菜園・夏蔬採收日",
    shortTitle: "夏蔬採收",
    day: "30",
    month: "MAY",
    weekday: "六",
    dateLabel: "30 MAY (六)",
    time: "08:30 - 11:30",
    duration: "3 hr",
    registered: 1,
    capacity: 10,
    price: 780,
    unit: "人",
    location: "後埕菜園",
    address: "台南市後壁區後埕菜園",
    instructor: "菜園阿良",
    summary: "小滿時節，菜園正盛。採瓜、剪辣椒、拔蘿蔔，自選 2kg 蔬果帶回家。",
    heroClass: "from-[#517c2d] to-[#8cac49]",
    highlights: ["認識夏季蔬菜", "親手採收蔬果", "菜園導覽", "帶回 2kg 當季蔬果"],
    notes: ["請戴帽子防曬", "可自備購物袋", "雨天可能延期"],
  },
];

export function getActivityById(id) {
  return activities.find((activity) => activity.id === id);
}
